//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Usuarios.Domain.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Usuarios.Domain.Shared.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CPF e invalido..
        /// </summary>
        internal static string CPF_INVALID {
            get {
                return ResourceManager.GetString("CPF_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo CPF deve ter 11 caracteres.
        /// </summary>
        internal static string CPF_INVALID_LENGTH {
            get {
                return ResourceManager.GetString("CPF_INVALID_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo CPF é obrigatório..
        /// </summary>
        internal static string CPF_REQUIRED {
            get {
                return ResourceManager.GetString("CPF_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato de E-mail Invalido.
        /// </summary>
        internal static string EMAIL_INVALID_FORMAT {
            get {
                return ResourceManager.GetString("EMAIL_INVALID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo e-mail deve ter no máximo 100 caracteres.
        /// </summary>
        internal static string EMAIL_LENGTH_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_LENGTH_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo E-mail é obrigatório..
        /// </summary>
        internal static string EMAIL_REQUIRED {
            get {
                return ResourceManager.GetString("EMAIL_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Nome Completo deve possuir entre 5 e 100 caracteres.
        /// </summary>
        internal static string NAME_LENGTH_INVALID {
            get {
                return ResourceManager.GetString("NAME_LENGTH_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Nome Completo é obrigatório..
        /// </summary>
        internal static string NAME_REQUIRED {
            get {
                return ResourceManager.GetString("NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo password é obrigatório.
        /// </summary>
        internal static string PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo password deve ter ao menos um numero.
        /// </summary>
        internal static string PASSWORD_REQUIRES_DIGIT {
            get {
                return ResourceManager.GetString("PASSWORD_REQUIRES_DIGIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo password deve ter ao menos uma letra minuscula.
        /// </summary>
        internal static string PASSWORD_REQUIRES_LOWERCASE {
            get {
                return ResourceManager.GetString("PASSWORD_REQUIRES_LOWERCASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo password deve ter ao menos um caracter especial.
        /// </summary>
        internal static string PASSWORD_REQUIRES_SPECIAL_CHAR {
            get {
                return ResourceManager.GetString("PASSWORD_REQUIRES_SPECIAL_CHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo password deve ter ao menos uma letra maiuscula.
        /// </summary>
        internal static string PASSWORD_REQUIRES_UPPERCASE {
            get {
                return ResourceManager.GetString("PASSWORD_REQUIRES_UPPERCASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo password deve ter no mínimo 8 caracteres.
        /// </summary>
        internal static string PASSWORD_TOO_SHORT {
            get {
                return ResourceManager.GetString("PASSWORD_TOO_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil invalido.
        /// </summary>
        internal static string PROFILE_INVALID {
            get {
                return ResourceManager.GetString("PROFILE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo solicitante não deve ser nulo.
        /// </summary>
        internal static string REQUESTER_REQUIRED {
            get {
                return ResourceManager.GetString("REQUESTER_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status invalido.
        /// </summary>
        internal static string STATUS_INVALID {
            get {
                return ResourceManager.GetString("STATUS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apenas administradores podem alterar o nível de acesso e status de usuários..
        /// </summary>
        internal static string USER_CANNOT_MODIFY_ACCESS_LEVEL {
            get {
                return ResourceManager.GetString("USER_CANNOT_MODIFY_ACCESS_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você não pode alterar seu próprio nível de acesso e status por segurança..
        /// </summary>
        internal static string USER_CANNOT_MODIFY_OWN_ACCESS_LEVEL {
            get {
                return ResourceManager.GetString("USER_CANNOT_MODIFY_OWN_ACCESS_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apenas o próprio usuário pode se deletar ou gestores da ONG podem remover outros usuários..
        /// </summary>
        internal static string USER_CANNOT_REMOVE {
            get {
                return ResourceManager.GetString("USER_CANNOT_REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível alterar um usuário deletado..
        /// </summary>
        internal static string USER_REMOVED {
            get {
                return ResourceManager.GetString("USER_REMOVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível alterar um usuário suspenso..
        /// </summary>
        internal static string USER_SUSPENDED {
            get {
                return ResourceManager.GetString("USER_SUSPENDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apenas o próprio usuário ou gestores da ONG podem alterar outros usuários..
        /// </summary>
        internal static string USRE_CANNOT_ALTER {
            get {
                return ResourceManager.GetString("USRE_CANNOT_ALTER", resourceCulture);
            }
        }
    }
}
