// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Usuarios.Infrastructure.Data;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identidade")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Usuarios.Domain.Entities.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("criado_por");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataModificacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_modificacao");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("modificado_por");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("nome_completo");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("perfil");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("senha_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.HasKey("Guid");

                    b.ToTable("usuario", "identidade");
                });

            modelBuilder.Entity("Usuarios.Domain.Entities.Usuarios.Usuario", b =>
                {
                    b.OwnsOne("Usuarios.Domain.Entities.Usuarios.Cpf", "Cpf", b1 =>
                        {
                            b1.Property<Guid>("UsuarioGuid")
                                .HasColumnType("uuid");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("varchar(11)")
                                .HasColumnName("cpf");

                            b1.HasKey("UsuarioGuid");

                            b1.HasIndex("Numero")
                                .IsUnique()
                                .HasDatabaseName("ix_usuarios_cpf");

                            b1.ToTable("usuario", "identidade");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioGuid");
                        });

                    b.OwnsOne("Usuarios.Domain.Entities.Usuarios.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UsuarioGuid")
                                .HasColumnType("uuid");

                            b1.Property<string>("Endereco")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("varchar(150)")
                                .HasColumnName("email");

                            b1.HasKey("UsuarioGuid");

                            b1.HasIndex("Endereco")
                                .IsUnique()
                                .HasDatabaseName("ix_usuarios_email");

                            b1.ToTable("usuario", "identidade");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioGuid");
                        });

                    b.Navigation("Cpf")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
